services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - MONGO_URI="mongodb://mongo:27017/backend-api"
  #   restart: unless-stopped

  # backend-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #   restart: unless-stopped
  #   profiles:
  #     - production

  backend-seed:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URI=mongodb://mongo:27017/backend-api
    depends_on:
      - mongoDb
    command: npm run seed
    volumes:
      - .:/app

  mongoDb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
