services:
  mongoDb:
    image: mongo
    container_name: c-cam-mongoDb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: c-cam
    volumes:
      - mongo-data:/data/db
    networks:
      - c-cam-network

  minio:
    image: minio/minio:latest
    container_name: c-cam-minio
    restart: unless-stopped
    ports:
      - "29000:9000"
      - "29001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_REGION: us-east-1
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - c-cam-network

networks:
  c-cam-network:
    driver: bridge

volumes:
  mongo-data:
